"""
OT-023 graq_edit single-pass hardening — pre-publish gate tests.

# —— graqle:intelligence ——
# module: tests.test_generation.test_ot023_prepublish
# risk: HIGH (impact radius: 1 module)
# consumers: CI gate, publish workflow
# Generated by: graq_generate (90% confidence, adapted for tuple API)
"""
from __future__ import annotations

import pytest

from graqle.core.file_writer import (
    DiffApplicationError,
    _apply_patch_to_lines,
    apply_diff,
)


# ---------------------------------------------------------------------------
# Test 1 — happy path: delete + insert in a 50-line file
# ---------------------------------------------------------------------------

class TestEditSinglePassHappyPath:
    def test_edit_single_pass_happy_path(self):
        # Build a 50-line file: "# line 0\n" … "# line 49\n"
        lines = [f"# line {n}\n" for n in range(50)]

        # Delete indices 10, 11, 12 and insert 3 replacements.
        # Context lines are the originals at indices 9 and 13.
        diff_ops = [
            (" ", "# line 9"),
            ("-", "# line 10"),
            ("-", "# line 11"),
            ("-", "# line 12"),
            ("+", "# replacement A\n"),
            ("+", "# replacement B\n"),
            ("+", "# replacement C\n"),
            (" ", "# line 13"),
        ]

        result = _apply_patch_to_lines(lines, diff_ops)

        # Lines before the edit are unchanged.
        assert result[:10] == lines[:10], "Pre-edit lines must be byte-for-byte identical"

        # Replacements appear at the correct positions.
        assert result[10] == "# replacement A\n"
        assert result[11] == "# replacement B\n"
        assert result[12] == "# replacement C\n"

        # Lines after the edit are unchanged (original indices 13-49).
        assert result[13:] == lines[13:], "Post-edit lines must be byte-for-byte identical"

        # Total length is unchanged (deleted 3, inserted 3).
        assert len(result) == 50


# ---------------------------------------------------------------------------
# Test 2 — duplicate lines: positional coherence via surrounding context
# ---------------------------------------------------------------------------

class TestEditDuplicateLinesPositionalCoherence:
    def test_edit_duplicate_lines_positional_coherence(self):
        # 80-line file; indices 10, 25, 40, 55, 70 all contain "    return None\n".
        duplicate = "    return None\n"
        lines: list[str] = []
        duplicate_indices = {10, 25, 40, 55, 70}
        for i in range(80):
            if i in duplicate_indices:
                lines.append(duplicate)
            else:
                lines.append(f"# unique line {i}\n")

        # Target the instance at index 40 using its unique neighbours (39 and 41).
        diff_ops = [
            (" ", "# unique line 39"),
            ("-", "    return None"),
            ("+", "    return 42\n"),
            (" ", "# unique line 41"),
        ]

        result = _apply_patch_to_lines(lines, diff_ops)

        # Only index 40 is changed.
        assert result[40] == "    return 42\n", "Target instance must be replaced"

        # All other duplicate instances are untouched.
        for idx in (10, 25, 55, 70):
            assert result[idx] == duplicate, f"Instance at index {idx} must be untouched"

        # Total length unchanged (1 deleted, 1 inserted).
        assert len(result) == 80

        # Surrounding unique lines are preserved.
        assert result[39] == lines[39]
        assert result[41] == lines[41]


# ---------------------------------------------------------------------------
# Test 3 — large file auto-scaling max_gap
# ---------------------------------------------------------------------------

class TestEditLargeFileAutoScalingMaxGap:
    def test_edit_large_file_auto_scaling_max_gap(self):
        # 5000-line file; unique function at line 4500.
        lines = [f"# line {n}\n" for n in range(5000)]
        lines[4500] = "def unique_function_4500():\n"

        diff_ops = [
            (" ", "# line 4498"),
            ("-", "# line 4499"),
            ("+", "# patched 4499\n"),
            (" ", "def unique_function_4500():"),
        ]

        # max_gap=0 → auto mode → max(50, 5000//5) = 1000
        result = _apply_patch_to_lines(lines, diff_ops, max_gap=0)
        assert "# patched 4499" in result[4499]

        # max_gap=10 is too small — context lines at 4498 and 4500 are fine
        # (gap=2), but the gap from line 0 (first scan position) to 4498 is huge.
        # However, since we only have 2 match positions with gap=2, max_gap=10
        # should actually pass. Let's test with max_gap=1 to force failure
        # on the gap between the two context positions if they're >1 apart.
        # Actually the gap between 4498 and 4500 is only 2, so even max_gap=1
        # would fail. Let's use a scenario where context lines are far apart:
        diff_ops_far = [
            (" ", "# line 0"),
            (" ", "def unique_function_4500():"),
            ("+", "    # inserted\n"),
        ]
        # Gap between line 0 and line 4500 = 4500 > 10
        with pytest.raises(DiffApplicationError, match="non-contiguous"):
            _apply_patch_to_lines(lines, diff_ops_far, max_gap=10)


# ---------------------------------------------------------------------------
# Test 4 — unmatched delete raises DiffApplicationError
# ---------------------------------------------------------------------------

class TestEditUnmatchedDeleteRaises:
    def test_edit_unmatched_delete_raises(self):
        lines = [f"# line {n}\n" for n in range(20)]

        diff_ops = [
            (" ", "# line 5"),
            ("-", "THIS_LINE_DOES_NOT_EXIST"),
            (" ", "# line 6"),
        ]

        with pytest.raises(DiffApplicationError) as exc_info:
            _apply_patch_to_lines(lines, diff_ops)

        assert "delete line not found" in str(exc_info.value).lower(), (
            "Error message must mention 'delete line not found'"
        )


# ---------------------------------------------------------------------------
# Test 5 — delete preserves intervening lines
# ---------------------------------------------------------------------------

class TestEditDeletePreservesInterveningLines:
    def test_edit_delete_preserves_intervening_lines(self):
        lines = ["A\n", "B\n", "C\n", "D\n", "E\n"]

        diff_ops = [
            (" ", "A"),
            ("-", "B"),
            (" ", "C"),
            ("-", "D"),
            (" ", "E"),
        ]

        result = _apply_patch_to_lines(lines, diff_ops)

        assert result == ["A\n", "C\n", "E\n"], (
            f"Expected ['A\\n', 'C\\n', 'E\\n'], got {result!r}"
        )


# ---------------------------------------------------------------------------
# Test 6 — threshold and max_gap input validation
# ---------------------------------------------------------------------------

class TestEditThresholdAndMaxGapInputValidation:
    """Boundary-value tests for the threshold and max_gap parameters."""

    def _simple_lines(self) -> list[str]:
        return [f"line {n}\n" for n in range(10)]

    def _simple_ops(self) -> list[tuple[str, str]]:
        return [
            (" ", "line 3"),
            ("-", "line 4"),
            ("+", "replaced\n"),
            (" ", "line 5"),
        ]

    def test_threshold_zero_raises_value_error(self):
        with pytest.raises(ValueError):
            _apply_patch_to_lines(
                self._simple_lines(), self._simple_ops(),
                context_match_threshold=0.0,
            )

    def test_threshold_above_one_raises_value_error(self):
        with pytest.raises(ValueError):
            _apply_patch_to_lines(
                self._simple_lines(), self._simple_ops(),
                context_match_threshold=1.5,
            )

    def test_threshold_negative_raises_value_error(self):
        with pytest.raises(ValueError):
            _apply_patch_to_lines(
                self._simple_lines(), self._simple_ops(),
                context_match_threshold=-0.1,
            )

    def test_max_gap_negative_raises_value_error(self):
        with pytest.raises(ValueError):
            _apply_patch_to_lines(
                self._simple_lines(), self._simple_ops(),
                max_gap=-1,
            )

    def test_threshold_one_with_exact_context_succeeds(self):
        # threshold=1.0 requires exact match; context lines are exact.
        result = _apply_patch_to_lines(
            self._simple_lines(), self._simple_ops(),
            context_match_threshold=1.0,
        )
        assert result[4] == "replaced\n"

    def test_max_gap_zero_auto_mode_succeeds(self):
        # max_gap=0 triggers auto mode; should not raise.
        result = _apply_patch_to_lines(
            self._simple_lines(), self._simple_ops(),
            max_gap=0,
        )
        assert result[4] == "replaced\n"


# ---------------------------------------------------------------------------
# Test 7 — non-Python YAML with duplicates: section-scoped replacement
# ---------------------------------------------------------------------------

class TestEditNonPythonYamlWithDuplicates:
    def test_edit_non_python_yaml_with_duplicates(self):
        yaml_content = (
            "# Section 1\n"
            "service: alpha\n"
            "timeout: 30\n"
            "retries: 3\n"
            "\n"
            "# Section 2\n"
            "service: beta\n"
            "timeout: 30\n"
            "retries: 5\n"
            "\n"
            "# Section 3\n"
            "service: gamma\n"
            "timeout: 30\n"
            "retries: 2\n"
        )
        lines = yaml_content.splitlines(keepends=True)

        # Indices (0-based):
        #  0: "# Section 1\n"
        #  1: "service: alpha\n"
        #  2: "timeout: 30\n"   ← first occurrence
        #  5: "# Section 2\n"
        #  6: "service: beta\n"
        #  7: "timeout: 30\n"   ← TARGET (second occurrence)
        #  8: "retries: 5\n"
        # 10: "# Section 3\n"
        # 12: "timeout: 30\n"   ← third occurrence

        # Use unique surrounding lines as context to pin to section 2.
        diff_ops = [
            (" ", "service: beta"),    # index 6 — unique to section 2
            ("-", "timeout: 30"),
            ("+", "timeout: 60\n"),
            (" ", "retries: 5"),       # index 8 — unique to section 2
        ]

        result = _apply_patch_to_lines(lines, diff_ops)

        # Second occurrence (index 7) is replaced.
        assert result[7] == "timeout: 60\n", (
            "Second 'timeout: 30' must be replaced with 'timeout: 60'"
        )

        # First and third occurrences are untouched.
        assert result[2] == "timeout: 30\n", "First occurrence must be untouched"
        assert result[12] == "timeout: 30\n", "Third occurrence must be untouched"

        # Total length unchanged (1 deleted, 1 inserted).
        assert len(result) == len(lines)

        # Surrounding unique lines preserved.
        assert result[6] == "service: beta\n"
        assert result[8] == "retries: 5\n"
