"""
OT-056 — graq_generate signature injection pre-publish gate tests.

7 tests verifying that _handle_generate correctly injects function/method
signatures into the generation prompt via KG lookup and AST fallback.

Generated by: graq_generate (90% confidence) + graq_reason (92% confidence)
Mock pattern: proven from test_ot056_signatures.py (4/4 pass)
"""
from __future__ import annotations

import ast
import json
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from graqle.plugins.mcp_dev_server import KogniDevServer


# ---------------------------------------------------------------------------
# Helpers (proven mock pattern from test_ot056_signatures.py)
# ---------------------------------------------------------------------------

def _make_node(
    label: str,
    entity_type: str = "Function",
    description: str = "",
    signature: str | None = None,
) -> MagicMock:
    node = MagicMock()
    node.label = label
    node.entity_type = entity_type
    node.description = description
    node.properties = {"signature": signature} if signature else {}
    return node


def _make_server(nodes: dict[str, MagicMock]) -> KogniDevServer:
    srv = KogniDevServer.__new__(KogniDevServer)
    srv.config_path = "graqle.yaml"
    srv.read_only = False
    srv._config = MagicMock()
    srv._graph_file = "graqle.json"
    srv._graph_mtime = 9999999999.0

    graph = MagicMock()
    graph.nodes = nodes
    graph.edges = {}
    graph._activate_subgraph = MagicMock(return_value=list(nodes.keys()))
    graph.config.activation.strategy = "spread"

    backend = MagicMock()
    gen_result = MagicMock()
    gen_result.text = (
        "--- a/t.py\n+++ b/t.py\n@@ -1,1 +1,2 @@\n+# gen\n\nSUMMARY: Done."
    )
    gen_result.tokens_used = 100
    backend.generate = AsyncMock(return_value=gen_result)
    backend.cost_per_1k_tokens = 0.003
    graph._get_backend_for_node = MagicMock(return_value=backend)
    srv._graph = graph
    return srv


async def _run_generate(server, description, file_path=None):
    args = {"description": description}
    if file_path:
        args["file_path"] = file_path
    with patch("graqle.cloud.credentials.load_credentials") as mc:
        mc.return_value = MagicMock(plan="team")
        with patch.object(server, "_handle_preflight", new=AsyncMock(
            return_value=json.dumps({
                "risk_level": "low", "warnings": [], "lessons": [],
                "safety_boundaries": [], "adrs": [],
            })
        )):
            with patch.object(server, "_handle_safety_check", new=AsyncMock(
                return_value=json.dumps({"overall_risk": "low"})
            )):
                # Allow tmp_path files past the project-root check
                with patch.object(
                    server, "_resolve_file_path",
                    side_effect=lambda p: p,
                ):
                    return json.loads(await server._handle_generate(args))


def _get_prompt(server) -> str:
    backend = server._graph._get_backend_for_node.return_value
    return backend.generate.call_args[0][0]


# ---------------------------------------------------------------------------
# Test 1 — KG signature happy path
# ---------------------------------------------------------------------------

class TestOT056PrePublish:

    @pytest.mark.asyncio
    async def test_generate_kg_signature_happy_path(self) -> None:
        """KG Function node carries full signature → exact params in prompt."""
        node = _make_node(
            "process", "Function", "Process incoming data",
            signature="def process(data: list[str], threshold: float = 0.5) -> bool",
        )
        server = _make_server({"process": node})
        await _run_generate(server, "add validation to process function")
        prompt = _get_prompt(server)

        assert "data: list[str]" in prompt
        assert "threshold: float" in prompt
        assert "EXACT parameter names" in prompt

    # -----------------------------------------------------------------------
    # Test 2 — AST fallback when KG is stale
    # -----------------------------------------------------------------------

    @pytest.mark.asyncio
    async def test_generate_ast_fallback_stale_kg(self, tmp_path: Path) -> None:
        """KG has no signature → AST extracts from real source file."""
        target = tmp_path / "transform.py"
        target.write_text(
            "def transform(input_df, columns: list[str]) -> None:\n"
            "    pass\n",
            encoding="utf-8",
        )

        node = _make_node("transform", "Function", "Transform data")
        server = _make_server({"transform": node})
        await _run_generate(server, "add logging", file_path=str(target))
        prompt = _get_prompt(server)

        assert "input_df" in prompt, "AST-extracted param must appear"
        assert "columns" in prompt, "AST-extracted param must appear"

    # -----------------------------------------------------------------------
    # Test 3 — Method qualified name resolution
    # -----------------------------------------------------------------------

    @pytest.mark.asyncio
    async def test_generate_method_qualified_name_resolution(self, tmp_path: Path) -> None:
        """ClassName.method resolved via qualified AST extraction."""
        target = tmp_path / "payment.py"
        target.write_text(
            "class PaymentService:\n"
            "    def charge(self, amount: float, idempotency_key: str) -> dict:\n"
            "        pass\n",
            encoding="utf-8",
        )

        node = _make_node("PaymentService.charge", "Method", "Charge payment")
        server = _make_server({"PaymentService.charge": node})
        await _run_generate(server, "add retry logic", file_path=str(target))
        prompt = _get_prompt(server)

        assert "idempotency_key" in prompt
        assert "amount" in prompt

    # -----------------------------------------------------------------------
    # Test 4 — Bare name fallback for dotted labels
    # -----------------------------------------------------------------------

    @pytest.mark.asyncio
    async def test_generate_label_lookup_bare_name_fallback(self, tmp_path: Path) -> None:
        """KG label 'utils.helpers.parse_config' → bare name fallback works."""
        target = tmp_path / "helpers.py"
        target.write_text(
            "def parse_config(config_path: str, strict: bool = True) -> dict:\n"
            "    pass\n",
            encoding="utf-8",
        )

        node = _make_node("utils.helpers.parse_config", "Function", "Parse config")
        server = _make_server({"utils.helpers.parse_config": node})
        await _run_generate(server, "add yaml support", file_path=str(target))
        prompt = _get_prompt(server)

        assert "config_path" in prompt, "Bare-name fallback must resolve"
        assert "strict" in prompt

    # -----------------------------------------------------------------------
    # Test 5 — Duplicate bare names disambiguation
    # -----------------------------------------------------------------------

    @pytest.mark.asyncio
    async def test_generate_duplicate_bare_names_disambiguation(self, tmp_path: Path) -> None:
        """Two nodes with same bare name → KG signature + AST fallback coexist."""
        target = tmp_path / "validators.py"
        target.write_text(
            "def validate(amount: float, currency: str) -> bool:\n"
            "    pass\n",
            encoding="utf-8",
        )

        auth_node = _make_node(
            "auth.validate", "Function", "Validate auth",
            signature="def validate(token: str) -> bool",
        )
        payment_node = _make_node("payment.validate", "Function", "Validate payment")

        server = _make_server({
            "auth.validate": auth_node,
            "payment.validate": payment_node,
        })
        await _run_generate(server, "add checks", file_path=str(target))
        prompt = _get_prompt(server)

        # auth.validate uses KG signature → "token"
        assert "token" in prompt, "auth.validate KG sig must inject 'token'"
        # payment.validate uses AST fallback → "amount"
        assert "amount" in prompt, "payment.validate AST fallback must inject 'amount'"

    # -----------------------------------------------------------------------
    # Test 6 — Non-Python file graceful degradation
    # -----------------------------------------------------------------------

    @pytest.mark.asyncio
    async def test_generate_non_python_file_graceful_degradation(self, tmp_path: Path) -> None:
        """TypeScript target → AST fallback skipped, no crash."""
        target = tmp_path / "handler.ts"
        target.write_text(
            "export function handleRequest(req: Request): Response {\n"
            "  return new Response('ok');\n"
            "}\n",
            encoding="utf-8",
        )

        node = _make_node("handleRequest", "Function", "Handle HTTP")
        server = _make_server({"handleRequest": node})
        result = await _run_generate(server, "add logging", file_path=str(target))

        # Must complete without error
        assert "error" not in result or result.get("error") is None

    # -----------------------------------------------------------------------
    # Test 7 — Malformed source AST resilience
    # -----------------------------------------------------------------------

    @pytest.mark.asyncio
    async def test_generate_malformed_source_ast_resilience(self, tmp_path: Path) -> None:
        """Broken .py file → AST fallback fails gracefully, generation completes."""
        target = tmp_path / "broken.py"
        broken_source = "def broken(x: int,\n    pass\n"
        target.write_text(broken_source, encoding="utf-8")

        # Confirm genuinely broken
        with pytest.raises(SyntaxError):
            ast.parse(broken_source)

        node = _make_node("broken", "Function", "A broken function")
        server = _make_server({"broken": node})
        result = await _run_generate(server, "fix syntax", file_path=str(target))

        # Must complete without crash
        assert "error" not in result or result.get("error") is None
        # Backend was still called
        backend = server._graph._get_backend_for_node.return_value
        assert backend.generate.called
