"""kogni init — set up governed development for any project.

Creates cognigraph.yaml, cognigraph.json (knowledge graph from scan),
.mcp.json (MCP server registration), CLAUDE.md (governance protocols),
and .gcc/ directory structure. This is the first thing users run.
"""

from __future__ import annotations

import json
import logging
import os
import re
from pathlib import Path
from typing import Any

import typer
import yaml
from rich.console import Console
from rich.panel import Panel
from rich.prompt import IntPrompt, Prompt
from rich.table import Table

console = Console()
logger = logging.getLogger("cognigraph.cli.init")

# ──────────────────────────────────────────────────────────────────────
# Backend / model registry
# ──────────────────────────────────────────────────────────────────────

BACKENDS: dict[str, dict[str, Any]] = {
    "anthropic": {
        "name": "Anthropic (Claude)",
        "models": [
            ("claude-haiku-4-5-20251001", "Claude Haiku — Fast + cheap ($0.001/query)", True),
            ("claude-sonnet-4-6", "Claude Sonnet — Balanced ($0.01/query)", False),
            ("claude-opus-4-6", "Claude Opus — Most capable ($0.05/query)", False),
        ],
        "api_key_env": "ANTHROPIC_API_KEY",
    },
    "openai": {
        "name": "OpenAI",
        "models": [
            ("gpt-4o-mini", "GPT-4o-mini — Fast + cheap ($0.002/query)", True),
            ("gpt-4o", "GPT-4o — Balanced ($0.01/query)", False),
        ],
        "api_key_env": "OPENAI_API_KEY",
    },
    "bedrock": {
        "name": "AWS Bedrock",
        "models": [
            (
                "anthropic.claude-haiku-4-5-20251001-v1:0",
                "Claude Haiku on Bedrock",
                True,
            ),
            (
                "anthropic.claude-sonnet-4-6-v1:0",
                "Claude Sonnet on Bedrock",
                False,
            ),
        ],
        "api_key_env": "AWS_DEFAULT_REGION",
    },
    "custom": {
        "name": "Custom OpenAI-compatible endpoint",
        "models": [],
        "api_key_env": "CUSTOM_API_KEY",
    },
}

# ──────────────────────────────────────────────────────────────────────
# CLAUDE.md content — THE product differentiator
# ──────────────────────────────────────────────────────────────────────

CLAUDE_MD_SECTION = r"""
# CogniGraph — Governed Development Protocol

> Auto-generated by `kogni init`. This section turns Claude Code into a
> governed, self-improving development agent using CogniGraph MCP tools,
> GCC context management, GSD structured work, and the Ralph Loop.

---

## MCP Tools Available

CogniGraph registers as an MCP server. The following tools are available
to Claude Code when the server is running (`kogni mcp serve`):

| Tool | Purpose | Example |
|------|---------|---------|
| `kogni context <service>` | Get 500-token focused context for a service | `kogni context auth-lambda` |
| `kogni run "<query>"` | Run a reasoning query over the knowledge graph | `kogni run "what calls the payments API?"` |
| `kogni inspect --stats` | Show graph statistics (nodes, edges, density) | `kogni inspect --stats` |
| `kogni scan repo .` | Re-scan the codebase and rebuild the knowledge graph | `kogni scan repo .` |

**Usage rule:** Before loading large files for context, check if `kogni context <name>` can provide what you need in 500 tokens instead of 20-60K.

---

## GCC Protocol — Global Context Controller

GCC keeps structured memory across sessions so no context is ever lost.

### Session Start (execute silently)
1. Read this `CLAUDE.md`
2. Read `.gcc/main.md` (global roadmap, ~300 tokens)
3. Read `.gcc/registry.md` (active branches, ~100 tokens)
4. Identify active branch from registry
5. Read `.gcc/branches/{active}/commit.md` (latest milestones, ~400 tokens)
6. Announce: "Resuming from COMMIT {N} on {branch}. Last: {summary}. Next: {next_steps}"

### During Work
- **COMMIT** after every completed milestone (feature, fix, test, deploy step)
- **Auto-COMMIT** every 30 minutes of active work — never lose progress
- **BRANCH** when starting a new feature or experiment
- **MERGE** when a branch achieves its purpose

### COMMIT Format
Append to `.gcc/branches/{branch}/commit.md`:
```markdown
### COMMIT {N} — {timestamp}
**Milestone:** {one-line summary}
**State:** WORKING | DONE | BLOCKED | HANDOFF
**Files Changed:**
- CREATED: {path} — {purpose}
- MODIFIED: {path} — {what changed}
**Key Decisions:**
- {decision and rationale}
**Next:**
- [ ] {immediate next step}
**Blockers:** {any blockers, or "None"}
```

### Session End
1. COMMIT current progress (even if incomplete — state: WORKING)
2. Update `.gcc/branches/{branch}/log.md` with session trace
3. Create checkpoint in `.gcc/checkpoints/`
4. Announce: "Session saved. COMMIT {N} on {branch}. Next: {next_steps}"

---

## GSD Protocol — Get Shit Done

GSD provides structured pre-work before execution. Spec before code.

### When to Use Full GSD
- New features spanning 3+ files
- Multi-session work
- Cross-system changes (frontend + backend + infra)

### Phases

**DISCUSS** — Clarify the problem before writing code:
1. What problem? Who benefits? What constraints?
2. Which systems are touched?
3. Produce `context.md` with problem statement, scope, success criteria

**PLAN** — Break into atomic tasks:
1. Break success criteria into ordered phases
2. Each task = one commit, independently revertable
3. Produce `plan.md` with ordered tasks + verification methods

**EXECUTE** — Work through the plan:
1. One task = one COMMIT, referencing plan task ID
2. After each task: run tests, lint, verify
3. Scope creep goes to "deferred" — never mid-sprint

**VERIFY** — Cross-reference THREE sources:
1. Evidence (actual outputs, test results)
2. Plan (all tasks checked off?)
3. Context (success criteria satisfied?)

---

## Ralph Loop — Autonomous Iteration

Ralph enables persistent fix-test-fix cycles with memory.

### Protocol
```
1. ENTRY: Receive task + binary completion criteria
2. WORK: Execute toward criteria
3. CHECK: Binary — PASS or FAIL
   PASS → COMMIT state: DONE → EXIT
   FAIL → COMMIT state: WORKING → increment counter
4. SAFETY: iteration_count >= 20 → COMMIT state: BLOCKED → EXIT
5. RE-FEED: Read last COMMIT → resume from step 2
```

### Safety Guards
| Guard | Default |
|-------|---------|
| max_iterations | 20 |
| commit_per_iteration | YES (never skip) |
| destructive_ops | BLOCKED (require user approval) |
| deploy_to_main | BLOCKED (require user approval) |
| scope_creep | BLOCKED (exit loop, re-DISCUSS) |

### Writing Good Criteria
- BAD: "Fix the auth and make it work"
- GOOD: "All auth tests pass. Login returns 200. Token refresh works. Output: DONE"

---

## Self-Improvement

After ANY correction from the user:
1. Add a one-liner lesson to `tasks/lessons-distilled.md`
2. Categorize: CRITICAL / HIGH / MEDIUM
3. Tag with domain: build | test | deploy | logic | api | db
4. Before starting any task, scan lessons for related failure patterns

---

## Configuration Reference

- `cognigraph.yaml` — Model backend, graph connector, activation strategy, cost budgets
- `cognigraph.json` — The knowledge graph (auto-generated by `kogni scan repo .`)
- `.mcp.json` — MCP server registration for Claude Code / Cursor / Windsurf
- `.gcc/` — Context controller state (commits, branches, checkpoints)

To re-scan the codebase: `kogni scan repo .`
To query the graph: `kogni run "your question"`
To get focused context: `kogni context <service-name>`
""".strip()

# ──────────────────────────────────────────────────────────────────────
# Repo scanning (enhanced from scan.py)
# ──────────────────────────────────────────────────────────────────────

_SKIP_DIRS = {
    "__pycache__",
    ".git",
    "node_modules",
    ".venv",
    "venv",
    ".next",
    ".nuxt",
    "dist",
    "build",
    ".tox",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    "egg-info",
    ".eggs",
}

_PYTHON_EXTS = {".py"}
_JS_TS_EXTS = {".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs"}
_CONFIG_NAMES = {
    "package.json",
    "pyproject.toml",
    "setup.py",
    "setup.cfg",
    "Cargo.toml",
    "go.mod",
    "Makefile",
    "Dockerfile",
    "docker-compose.yml",
    "docker-compose.yaml",
    ".env",
    ".env.example",
    "requirements.txt",
    "Pipfile",
}


def _should_skip(path: Path) -> bool:
    """Return True if *path* (or any ancestor) is in the skip set."""
    return any(part in _SKIP_DIRS or part.endswith(".egg-info") for part in path.parts)


def _detect_project_type(root: Path) -> str:
    """Detect whether the project is Python, Node, or monorepo."""
    has_python = (root / "pyproject.toml").exists() or (root / "setup.py").exists()
    has_node = (root / "package.json").exists()
    if has_python and has_node:
        return "monorepo"
    if has_node:
        return "node"
    return "python"


def _extract_python_imports(content: str) -> list[str]:
    """Return local-looking import targets from Python source."""
    imports: list[str] = []
    for line in content.splitlines():
        stripped = line.strip()
        if stripped.startswith("from ") or stripped.startswith("import "):
            match = re.match(r"(?:from|import)\s+([\w.]+)", stripped)
            if match:
                module = match.group(1)
                # Keep relative and dotted (likely local) imports
                if "." in module:
                    imports.append(module)
    return imports


def _extract_js_imports(content: str) -> list[str]:
    """Return local import paths from JS/TS source."""
    imports: list[str] = []
    for match in re.finditer(
        r"""(?:import|require)\s*\(?\s*['"]([./][^'"]+)['"]\s*\)?""", content
    ):
        imports.append(match.group(1))
    for match in re.finditer(r"""from\s+['"]([./][^'"]+)['"]""", content):
        imports.append(match.group(1))
    return imports


def scan_repository(root: Path) -> dict[str, Any]:
    """Scan a repository and return a NetworkX-compatible node-link dict.

    Returns the dict directly (no NetworkX dependency required at scan time
    for the init command — we build the structure manually).
    """
    nodes: list[dict[str, Any]] = []
    edges: list[dict[str, Any]] = []
    node_ids: set[str] = set()
    import_edges: list[tuple[str, str]] = []

    project_type = _detect_project_type(root)

    # ── Collect source files ────────────────────────────────────────
    source_exts = _PYTHON_EXTS | _JS_TS_EXTS

    for fpath in root.rglob("*"):
        if not fpath.is_file():
            continue
        if _should_skip(fpath):
            continue

        rel = fpath.relative_to(root)
        file_id = str(rel).replace("\\", "/")

        # Source files
        if fpath.suffix in source_exts:
            entity_type = "PythonModule" if fpath.suffix in _PYTHON_EXTS else "JSModule"
            nodes.append(
                {
                    "id": file_id,
                    "label": fpath.stem,
                    "type": entity_type,
                    "description": f"{entity_type}: {rel}",
                }
            )
            node_ids.add(file_id)

            # Directory node
            if len(rel.parts) > 1:
                dir_id = "/".join(rel.parts[:-1])
                if dir_id not in node_ids:
                    nodes.append(
                        {
                            "id": dir_id,
                            "label": rel.parts[-2],
                            "type": "Directory",
                            "description": f"Directory: {dir_id}",
                        }
                    )
                    node_ids.add(dir_id)
                edges.append(
                    {"source": dir_id, "target": file_id, "relationship": "CONTAINS"}
                )

            # Parse imports
            try:
                content = fpath.read_text(errors="ignore")
                if fpath.suffix in _PYTHON_EXTS:
                    for imp in _extract_python_imports(content):
                        target = imp.replace(".", "/") + ".py"
                        import_edges.append((file_id, target))
                elif fpath.suffix in _JS_TS_EXTS:
                    for imp in _extract_js_imports(content):
                        import_edges.append((file_id, imp))
            except Exception:
                pass

        # Config files
        elif fpath.name in _CONFIG_NAMES:
            if file_id not in node_ids:
                nodes.append(
                    {
                        "id": file_id,
                        "label": fpath.stem,
                        "type": "Config",
                        "description": f"Configuration: {fpath.name}",
                    }
                )
                node_ids.add(file_id)

        # Test files
        elif fpath.name.startswith("test_") or fpath.name.endswith("_test.py"):
            if file_id not in node_ids:
                nodes.append(
                    {
                        "id": file_id,
                        "label": fpath.stem,
                        "type": "TestModule",
                        "description": f"Test: {rel}",
                    }
                )
                node_ids.add(file_id)

    # ── Resolve import edges ────────────────────────────────────────
    for source, target in import_edges:
        # Try exact match and common variants
        candidates = [target]
        if not target.endswith((".py", ".js", ".ts", ".tsx", ".jsx")):
            candidates.extend([target + ext for ext in [".py", ".ts", ".js", "/index.ts", "/index.js"]])
        for candidate in candidates:
            if candidate in node_ids:
                edges.append(
                    {"source": source, "target": candidate, "relationship": "IMPORTS"}
                )
                break

    return {
        "directed": True,
        "multigraph": False,
        "graph": {"project_type": project_type},
        "nodes": nodes,
        "links": edges,
    }


# ──────────────────────────────────────────────────────────────────────
# File generators
# ──────────────────────────────────────────────────────────────────────


def _build_cognigraph_yaml(
    backend: str, model: str, api_key_ref: str
) -> str:
    """Return the contents of cognigraph.yaml."""
    cfg: dict[str, Any] = {
        "model": {
            "backend": backend if backend != "custom" else "api",
            "model": model,
            "api_key": api_key_ref,
        },
        "graph": {
            "connector": "networkx",
        },
        "activation": {
            "strategy": "pcst",
            "max_nodes": 20,
        },
        "orchestration": {
            "max_rounds": 3,
            "convergence_threshold": 0.92,
        },
        "cost": {
            "budget_per_query": 0.05,
        },
        "observer": {
            "enabled": True,
        },
        "governance": {
            "enabled": True,
        },
    }
    return yaml.dump(cfg, default_flow_style=False, sort_keys=False)


def _build_mcp_json() -> dict[str, Any]:
    """Return the .mcp.json structure for CogniGraph."""
    return {
        "mcpServers": {
            "cognigraph": {
                "type": "stdio",
                "command": "kogni",
                "args": ["mcp", "serve", "--config", "cognigraph.yaml"],
            }
        }
    }


def _build_gcc_main_md(root: Path) -> str:
    """Auto-generate .gcc/main.md from project README if it exists."""
    readme_path = root / "README.md"
    header = "# Project Roadmap\n\n"
    if readme_path.exists():
        try:
            content = readme_path.read_text(errors="ignore")
            # Extract first 30 lines as summary
            lines = content.splitlines()[:30]
            summary = "\n".join(lines)
            return header + f"## From README\n\n{summary}\n\n## Goals\n\n- [ ] Define project goals here\n"
        except Exception:
            pass
    return header + "## Goals\n\n- [ ] Define project goals here\n"


def _build_gcc_registry_md() -> str:
    """Return initial .gcc/registry.md content."""
    return (
        "# Branch Registry\n\n"
        "| Branch | Status | Owner | Last Active |\n"
        "|--------|--------|-------|-------------|\n"
        "| main | ACTIVE | — | — |\n"
    )


def _build_gcc_config_yaml() -> str:
    """Return .gcc/config.yaml content."""
    cfg = {
        "project": "auto-detected",
        "token_budget": {
            "session_start": 800,
            "max_gcc_overhead_pct": 5,
        },
        "auto_commit_interval_min": 30,
    }
    return yaml.dump(cfg, default_flow_style=False, sort_keys=False)


def _build_gcc_metadata_yaml() -> str:
    """Return initial branch metadata.yaml."""
    cfg = {
        "branch": "main",
        "parent": None,
        "status": "ACTIVE",
        "file_tree": [],
        "open_questions": [],
    }
    return yaml.dump(cfg, default_flow_style=False, sort_keys=False)


# ──────────────────────────────────────────────────────────────────────
# Interactive prompts
# ──────────────────────────────────────────────────────────────────────


def _prompt_backend() -> str:
    """Ask the user to pick a backend."""
    table = Table(title="Available Backends", show_header=True, header_style="bold cyan")
    table.add_column("#", style="dim", width=3)
    table.add_column("Backend", style="bold")
    table.add_column("Description")

    backend_keys = list(BACKENDS.keys())
    for i, key in enumerate(backend_keys, 1):
        table.add_row(str(i), key, BACKENDS[key]["name"])

    console.print(table)
    choice = IntPrompt.ask(
        "Choose a backend",
        default=1,
        choices=[str(i) for i in range(1, len(backend_keys) + 1)],
    )
    return backend_keys[choice - 1]


def _prompt_model(backend: str) -> str:
    """Ask the user to pick a model for the chosen backend."""
    models = BACKENDS[backend]["models"]
    if not models:
        return Prompt.ask("Enter model name or endpoint URL", default="gpt-4o-mini")

    table = Table(title=f"Models for {BACKENDS[backend]['name']}", show_header=True, header_style="bold cyan")
    table.add_column("#", style="dim", width=3)
    table.add_column("Model", style="bold")
    table.add_column("Description")
    table.add_column("Default", style="dim")

    for i, (model_id, desc, is_default) in enumerate(models, 1):
        table.add_row(str(i), model_id, desc, "yes" if is_default else "")

    console.print(table)

    default_idx = next(
        (i for i, (_, _, d) in enumerate(models, 1) if d), 1
    )
    choice = IntPrompt.ask(
        "Choose a model",
        default=default_idx,
        choices=[str(i) for i in range(1, len(models) + 1)],
    )
    return models[choice - 1][0]


def _prompt_api_key(backend: str) -> str:
    """Ask the user how to provide their API key. Returns a ${VAR} reference or raw key."""
    env_var = BACKENDS[backend]["api_key_env"]
    existing = os.environ.get(env_var)

    if existing:
        console.print(f"[green]Found ${env_var} in environment.[/green]")
        use_existing = Prompt.ask(
            f"Use ${{{env_var}}} from environment?",
            choices=["y", "n"],
            default="y",
        )
        if use_existing == "y":
            return f"${{{env_var}}}"

    console.print(f"\nHow should CogniGraph access your API key?")
    console.print(f"  [bold]1.[/bold] Environment variable ${{{env_var}}} (recommended)")
    console.print(f"  [bold]2.[/bold] Enter the key now (stored in cognigraph.yaml)")

    choice = IntPrompt.ask("Choice", default=1, choices=["1", "2"])

    if choice == 1:
        console.print(
            f"\n[dim]Set the variable before running kogni:[/dim]"
            f"\n  export {env_var}=your-key-here\n"
        )
        return f"${{{env_var}}}"
    else:
        key = Prompt.ask("Enter your API key", password=True)
        return key


# ──────────────────────────────────────────────────────────────────────
# File writers (with merge/append logic)
# ──────────────────────────────────────────────────────────────────────


def _write_cognigraph_yaml(root: Path, content: str) -> bool:
    """Write cognigraph.yaml. Returns True if created, False if existed."""
    target = root / "cognigraph.yaml"
    if target.exists():
        console.print(f"  [yellow]cognigraph.yaml already exists — overwriting[/yellow]")
    target.write_text(content, encoding="utf-8")
    return True


def _write_cognigraph_json(root: Path, graph_data: dict[str, Any]) -> bool:
    """Write cognigraph.json (knowledge graph)."""
    target = root / "cognigraph.json"
    if target.exists():
        console.print(f"  [yellow]cognigraph.json already exists — overwriting with fresh scan[/yellow]")
    target.write_text(json.dumps(graph_data, indent=2), encoding="utf-8")
    return True


def _write_mcp_json(root: Path) -> bool:
    """Write or merge .mcp.json."""
    target = root / ".mcp.json"
    mcp_entry = _build_mcp_json()

    if target.exists():
        try:
            existing = json.loads(target.read_text(encoding="utf-8"))
            if "mcpServers" not in existing:
                existing["mcpServers"] = {}
            if "cognigraph" in existing.get("mcpServers", {}):
                console.print(f"  [dim].mcp.json already has cognigraph entry — skipping[/dim]")
                return False
            existing["mcpServers"]["cognigraph"] = mcp_entry["mcpServers"]["cognigraph"]
            target.write_text(json.dumps(existing, indent=2), encoding="utf-8")
            console.print(f"  [green]Merged cognigraph into existing .mcp.json[/green]")
            return True
        except (json.JSONDecodeError, KeyError):
            console.print(f"  [yellow].mcp.json exists but is invalid — overwriting[/yellow]")

    target.write_text(json.dumps(mcp_entry, indent=2), encoding="utf-8")
    return True


def _write_claude_md(root: Path) -> bool:
    """Write or append to CLAUDE.md."""
    target = root / "CLAUDE.md"
    marker = "# CogniGraph — Governed Development Protocol"

    if target.exists():
        existing = target.read_text(encoding="utf-8")
        if marker in existing:
            console.print(f"  [dim]CLAUDE.md already has CogniGraph section — skipping[/dim]")
            return False
        # Append
        with open(target, "a", encoding="utf-8") as f:
            f.write("\n\n" + CLAUDE_MD_SECTION + "\n")
        console.print(f"  [green]Appended CogniGraph section to existing CLAUDE.md[/green]")
        return True

    target.write_text(CLAUDE_MD_SECTION + "\n", encoding="utf-8")
    return True


def _write_gcc_structure(root: Path) -> bool:
    """Create .gcc/ directory structure. Skips if it already exists."""
    gcc = root / ".gcc"
    if gcc.exists():
        console.print(f"  [dim].gcc/ already exists — skipping[/dim]")
        return False

    # Create directories
    (gcc / "branches" / "main").mkdir(parents=True, exist_ok=True)
    (gcc / "checkpoints").mkdir(parents=True, exist_ok=True)

    # Write files
    (gcc / "main.md").write_text(_build_gcc_main_md(root), encoding="utf-8")
    (gcc / "registry.md").write_text(_build_gcc_registry_md(), encoding="utf-8")
    (gcc / "config.yaml").write_text(_build_gcc_config_yaml(), encoding="utf-8")
    (gcc / "branches" / "main" / "commit.md").write_text(
        "# Commit Log — main\n\n", encoding="utf-8"
    )
    (gcc / "branches" / "main" / "log.md").write_text(
        "# Session Log — main\n\n", encoding="utf-8"
    )
    (gcc / "branches" / "main" / "metadata.yaml").write_text(
        _build_gcc_metadata_yaml(), encoding="utf-8"
    )
    # .gitkeep for checkpoints
    (gcc / "checkpoints" / ".gitkeep").write_text("", encoding="utf-8")

    return True


# ──────────────────────────────────────────────────────────────────────
# Main init command
# ──────────────────────────────────────────────────────────────────────


def init_command(
    path: str = typer.Argument(".", help="Project root directory"),
    backend: str | None = typer.Option(
        None, "--backend", "-b", help="Backend: anthropic, openai, bedrock, custom"
    ),
    model: str | None = typer.Option(
        None, "--model", "-m", help="Model identifier"
    ),
    api_key_env: str | None = typer.Option(
        None, "--api-key-env", help="Environment variable name for API key"
    ),
    api_key: str | None = typer.Option(
        None, "--api-key", help="API key value (prefer --api-key-env instead)"
    ),
    no_interactive: bool = typer.Option(
        False, "--no-interactive", help="Skip interactive prompts"
    ),
    no_scan: bool = typer.Option(
        False, "--no-scan", help="Skip repository scan"
    ),
    no_gcc: bool = typer.Option(
        False, "--no-gcc", help="Skip .gcc/ directory creation"
    ),
    no_claude_md: bool = typer.Option(
        False, "--no-claude-md", help="Skip CLAUDE.md creation"
    ),
    no_mcp: bool = typer.Option(
        False, "--no-mcp", help="Skip .mcp.json creation"
    ),
) -> None:
    """Initialize governed development for this project.

    Sets up CogniGraph with a knowledge graph, model configuration,
    MCP server registration, CLAUDE.md governance protocols, and
    GCC context management — everything needed for AI-governed development.

    \b
    Interactive (default):
        kogni init

    \b
    Non-interactive:
        kogni init --backend anthropic --model claude-haiku-4-5-20251001 \\
                   --api-key-env ANTHROPIC_API_KEY --no-interactive
    """
    root = Path(path).resolve()
    if not root.exists():
        console.print(f"[red]Path not found: {root}[/red]")
        raise typer.Exit(1)

    # ── Banner ──────────────────────────────────────────────────────
    console.print(
        Panel(
            "[bold cyan]CogniGraph[/bold cyan] — Graphs that think\n"
            "[dim]Setting up governed development for your project[/dim]",
            border_style="cyan",
        )
    )
    console.print(f"Project root: [bold]{root}[/bold]\n")

    # ── Step 1: Gather configuration ────────────────────────────────
    if no_interactive:
        # Non-interactive: use provided flags or defaults
        chosen_backend = backend or "anthropic"
        if chosen_backend not in BACKENDS:
            console.print(
                f"[red]Unknown backend '{chosen_backend}'. "
                f"Choose from: {', '.join(BACKENDS.keys())}[/red]"
            )
            raise typer.Exit(1)

        chosen_model = model
        if not chosen_model:
            models = BACKENDS[chosen_backend]["models"]
            chosen_model = next(
                (m for m, _, d in models if d),
                models[0][0] if models else "gpt-4o-mini",
            )

        if api_key:
            api_key_ref = api_key
        elif api_key_env:
            api_key_ref = f"${{{api_key_env}}}"
        else:
            api_key_ref = f"${{{BACKENDS[chosen_backend]['api_key_env']}}}"
    else:
        # Interactive
        console.print("[bold]Step 1/3:[/bold] Choose your AI backend\n")
        chosen_backend = _prompt_backend()

        console.print(f"\n[bold]Step 2/3:[/bold] Choose a model\n")
        chosen_model = _prompt_model(chosen_backend)

        console.print(f"\n[bold]Step 3/3:[/bold] API key configuration\n")
        api_key_ref = _prompt_api_key(chosen_backend)

    console.print(
        f"\n[bold green]Configuration:[/bold green] "
        f"{BACKENDS[chosen_backend]['name']} / {chosen_model}\n"
    )

    # ── Step 2: Scan repository ─────────────────────────────────────
    graph_data: dict[str, Any] | None = None
    if not no_scan:
        console.print("[bold]Scanning repository...[/bold]")
        graph_data = scan_repository(root)
        node_count = len(graph_data["nodes"])
        edge_count = len(graph_data["links"])
        project_type = graph_data["graph"].get("project_type", "unknown")
        console.print(
            f"  Found [cyan]{node_count}[/cyan] nodes, "
            f"[cyan]{edge_count}[/cyan] edges "
            f"([dim]{project_type} project[/dim])\n"
        )

    # ── Step 3: Write files ─────────────────────────────────────────
    console.print("[bold]Creating files...[/bold]")

    # cognigraph.yaml
    yaml_content = _build_cognigraph_yaml(chosen_backend, chosen_model, api_key_ref)
    _write_cognigraph_yaml(root, yaml_content)
    console.print(f"  [green]+[/green] cognigraph.yaml")

    # cognigraph.json
    if graph_data is not None:
        _write_cognigraph_json(root, graph_data)
        console.print(f"  [green]+[/green] cognigraph.json")

    # .mcp.json
    if not no_mcp:
        _write_mcp_json(root)
        console.print(f"  [green]+[/green] .mcp.json")

    # CLAUDE.md
    if not no_claude_md:
        _write_claude_md(root)
        console.print(f"  [green]+[/green] CLAUDE.md")

    # .gcc/
    if not no_gcc:
        created = _write_gcc_structure(root)
        if created:
            console.print(f"  [green]+[/green] .gcc/ (context controller)")

    # ── Done ────────────────────────────────────────────────────────
    console.print()
    console.print(
        Panel(
            "[bold green]Project initialized![/bold green]\n\n"
            "Next steps:\n"
            "  1. [bold]kogni scan repo .[/bold]    — rebuild the knowledge graph anytime\n"
            "  2. [bold]kogni context <name>[/bold] — get focused context for a service\n"
            "  3. [bold]kogni run \"query\"[/bold]    — reason over the knowledge graph\n"
            "  4. [bold]kogni inspect --stats[/bold] — view graph statistics\n\n"
            "[dim]CLAUDE.md now contains GCC + GSD + Ralph Loop protocols.\n"
            "Claude Code will use these automatically.[/dim]",
            border_style="green",
            title="Done",
        )
    )
