"""GraQle shipped documentation.

Machine-readable artifacts that travel with the package so users can
introspect their installed SDK without network access. Primary artifact:
mcp-tool-inventory-v{VERSION}.md (generated by scripts/generate_mcp_inventory.py).
"""
