"""T09 (v0.51.6) — Generate MCP tool inventory markdown.

Introspects graqle.plugins.mcp_dev_server.TOOL_DEFINITIONS at build time
and emits a markdown table: name | description | input schema summary.

Output path (default): graqle-sdk/graqle/docs/mcp-tool-inventory-v{VERSION}.md
The generated file is checked in and shipped in the wheel via
pyproject.toml [tool.hatch.build.targets.wheel] artifacts.

Usage:
    python scripts/generate_mcp_inventory.py
    python scripts/generate_mcp_inventory.py --check    # fail if drift
    python scripts/generate_mcp_inventory.py --out PATH
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Make the source tree importable when run standalone
_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT))


def _schema_summary(schema: dict) -> str:
    """One-liner describing the inputSchema properties."""
    props = schema.get("properties", {}) if isinstance(schema, dict) else {}
    if not props:
        return "_(no args)_"
    required = set(schema.get("required", []))
    parts = []
    for name, spec in props.items():
        t = spec.get("type", "?") if isinstance(spec, dict) else "?"
        flag = "*" if name in required else ""
        parts.append(f"`{name}{flag}: {t}`")
    return ", ".join(parts)


def _render_markdown(tool_definitions: list, version: str) -> str:
    lines: list[str] = []
    lines.append(f"# GraQle MCP Tool Inventory — v{version}")
    lines.append("")
    lines.append(f"Total tools: **{len(tool_definitions)}**")
    lines.append("")
    lines.append("Auto-generated by `scripts/generate_mcp_inventory.py`. ")
    lines.append("Do not edit by hand. Re-run after adding or removing MCP tools.")
    lines.append("")
    lines.append("Required args marked with `*`.")
    lines.append("")
    lines.append("| Tool | Description | Args |")
    lines.append("|---|---|---|")
    for tool in sorted(tool_definitions, key=lambda t: t["name"]):
        name = tool["name"]
        desc = tool.get("description", "").replace("\n", " ").replace("|", "\\|")
        # Trim long descriptions to keep table scannable
        if len(desc) > 180:
            desc = desc[:177] + "..."
        args = _schema_summary(tool.get("inputSchema", {}))
        lines.append(f"| `{name}` | {desc} | {args} |")
    lines.append("")
    return "\n".join(lines)


def _read_version() -> str:
    ver_file = _ROOT / "graqle" / "__version__.py"
    if not ver_file.exists():
        return "unknown"
    for line in ver_file.read_text(encoding="utf-8").splitlines():
        if line.startswith("__version__"):
            return line.split("=", 1)[1].strip().strip('"').strip("'")
    return "unknown"


def generate(out_path: Path | None = None) -> Path:
    from graqle.plugins.mcp_dev_server import TOOL_DEFINITIONS

    version = _read_version()
    docs_dir = _ROOT / "graqle" / "docs"
    docs_dir.mkdir(parents=True, exist_ok=True)
    if out_path is None:
        out_path = docs_dir / f"mcp-tool-inventory-v{version}.md"

    md = _render_markdown(list(TOOL_DEFINITIONS), version)
    out_path.write_text(md, encoding="utf-8")
    return out_path


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate MCP tool inventory.")
    parser.add_argument("--out", type=Path, default=None, help="Output path.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if generated content differs from on-disk (CI gate).",
    )
    args = parser.parse_args()

    if args.check:
        from graqle.plugins.mcp_dev_server import TOOL_DEFINITIONS

        version = _read_version()
        target = args.out or (_ROOT / "graqle" / "docs" / f"mcp-tool-inventory-v{version}.md")
        if not target.exists():
            print(f"ERROR: inventory missing: {target}", file=sys.stderr)
            return 1
        expected = _render_markdown(list(TOOL_DEFINITIONS), version)
        actual = target.read_text(encoding="utf-8")
        if expected != actual:
            print(
                "ERROR: MCP tool inventory is stale. Run: "
                "python scripts/generate_mcp_inventory.py",
                file=sys.stderr,
            )
            return 1
        print(f"OK: {target} is up-to-date ({len(TOOL_DEFINITIONS)} tools).")
        return 0

    out = generate(args.out)
    print(f"Wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
